server:
  port: 8080
  servlet:
    context-path: /api

#db configuration
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: "jdbc:mysql://localhost:3306/sunflower"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



jwt:
  signerKey: "ZcCAeQKy0ly5bPdCVHM8bLQp5KJX9eczTqZl7zhjzK42U7SXfALZcWpSjitA5tLX"
  valid-duration: 36000 # in second .
  refreshable-duration: 360000 # in seconds .

springdoc:
  swagger-ui:
    operations-sorter: method #sort by http method
    path: /swagger-ui.html
  api-docs:
    path: /api-docs